import React, { useCallback, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import axiosClient from "@/libraries/axiosClient";
import Image from "next/image";
import Header from "@/layouts/Header";
import Footer from "@/layouts/Footer";

function ListProductsOfCategory({ products, searchProductsByCategory }) {
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container-fluid bg-secondary mb-5">
        <div
          className="d-flex flex-column align-items-center justify-content-center"
          style={{ minHeight: 300 }}
        >
          <h1 className="font-weight-semi-bold text-uppercase mb-3">
            Our Shop
          </h1>
          <div className="d-inline-flex">
            <p className="m-0">
              <a href="">Home</a>
            </p>
            <p className="m-0 px-2">-</p>
            <p className="m-0">Shop</p>
          </div>
        </div>
      </div>
      <div className="container-fluid pt-5">
        <div className="row px-xl-5">
          {/* Shop Sidebar Start */}
          <div className="col-lg-3 col-md-12">
            {/* Category start */}
            <div className="border-bottom mb-4 pb-4">
              <h5 className="font-weight-semi-bold mb-4">Filter by Category</h5>
              <form>
                {searchProductsByCategory.map((cate) => (
                  <Link key={cate._id} href={`/`}>
                    <div
                      className="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3"
                      style={{ fontSize: "17px" }}
                    >
                      <input
                        type="checkbox"
                        className="custom-control-input"
                        id="category"
                      />
                      <label
                        className="custom-control-label"
                        htmlFor="category"
                      >
                        {cate.name}
                      </label>
                      <span className="badge font-weight-normal">
                        {cate.totalProduct}
                      </span>
                    </div>
                  </Link>
                ))}
              </form>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}

export default ListProductsOfCategory;

export async function getServerSideProps(req) {
  try {
    const { params } = req;
    const response = await axiosClient.get(`/user/categories/${params.id}`);
    // const response1 = await axiosClient.get("/user/products");
        const response2 = await axiosClient.get(
          "/questions/searchproductsbycategory"
        );
    return {
      props: {
        product: response.data.payload,
        productsOfCategoryShop: response2.data.payload,
        
      },
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}
// getServerSideProps - Server-Side Rendering
// export async function getServerSideProps() {
//   try {
//     const response = await axiosClient.get("/user/products");
//     const response1 = await axiosClient.get(
//       "/questions/productsofcategoryshop"
//     );

//     return {
//       props: {
//         products: response.data.payload,
//         productsOfCategoryShop: response1.data.payload,
//       },

//       // revalidate: 24 * 60 * 60,
//     };
//   } catch (error) {
//     return {
//       notFound: true,
//     };
//   }
// }

